"""Golden vectors for the crop the network input is taken from.

The C++ segmenter reproduces the preprocessing the model was trained under, and the
crop is the part of it that has to be exactly right: it is aspect-preserving so that the
resize after it is isotropic, which is what keeps curvature meaningful, and a region
that is off by a pixel tilts the ground plane the calibration was fitted against.

That arithmetic is small, integer, and full of rounding decisions — ``round`` breaking
ties to even, floor division on the centring, a tolerance below which a frame is left
uncropped. Exactly the kind of code where a port looks right and is not. So it gets the
same treatment as the rest of the port: the Python reference emits what it computes, and
the C++ test asserts it computes the same.

Covers the resolutions the project actually reads (CurveLanes, TuSimple, KITTI, common
dashcam sizes), plus the awkward cases: frames already at the target aspect, frames
taller than wide, and sizes chosen to land the rounding exactly on a half.

    python -m scripts.export_preprocess_vectors
"""

from __future__ import annotations

from pathlib import Path

from src.data.transforms import DEFAULT_SKY_FRAC, DEFAULT_TARGET_SIZE

OUT = Path("deploy/test/golden/preprocess.txt")

# (source width, source height, why it is here)
SOURCES = [
    (1280, 720, "TuSimple, and 720p dashcam footage"),
    (1242, 375, "KITTI, much wider than the target aspect"),
    (1640, 590, "CurveLanes, the most common native size"),
    (2560, 1440, "CurveLanes, the large frames"),
    (1570, 660, "CurveLanes, the odd aspect excluded from training"),
    (1920, 1080, "1080p, already exactly at the target aspect"),
    (1024, 576, "smaller, exactly at the target aspect"),
    (640, 480, "4:3, taller than the target aspect"),
    (480, 640, "portrait, much taller than the target aspect"),
    (1281, 721, "odd by one, so the centring divisions do not divide evenly"),
    (911, 512, "chosen so the aspect crop lands on a half"),
    (1000, 563, "close to the target aspect but outside the tolerance"),
    (513, 289, "barely larger than the network input"),
    (512, 288, "exactly the network input"),
]

# Sky fractions: the default the model was trained under, plus the edges.
SKY_FRACS = [DEFAULT_SKY_FRAC, 0.0, 0.15, 0.5]


def center_crop_aspect(w: int, h: int, target: tuple[int, int]) -> tuple[int, int, int, int]:
    """The region scripts/infer_sequence._center_crop_aspect keeps, as x, y, w, h."""
    tw, th = target
    tar = tw / th
    cur = w / h
    if abs(cur - tar) < 1e-3:
        return 0, 0, w, h
    if cur > tar:
        nw = int(round(h * tar))
        return (w - nw) // 2, 0, nw, h
    nh = int(round(w / tar))
    return 0, (h - nh) // 2, w, nh


def geometry_crop(w: int, h: int, target: tuple[int, int],
                  sky_frac: float) -> tuple[int, int, int, int]:
    """The region src.data.transforms.preprocess_geometry resizes from, as x, y, w, h."""
    tw, th = target
    tar = tw / th
    top = min(int(round(h * sky_frac)), h - 1)
    x, y = 0, top
    h = h - top
    cur = w / h
    if cur > tar:
        nw = int(round(h * tar))
        x += (w - nw) // 2
        w = nw
    elif cur < tar:
        nh = int(round(w / tar))
        y += h - nh
        h = nh
    return x, y, w, h


def main() -> None:
    target = DEFAULT_TARGET_SIZE
    lines = [
        "# Region of the source frame the network input is resized from.",
        "# Generated by scripts/export_preprocess_vectors.py; do not edit.",
        f"target {target[0]} {target[1]}",
        "# src_w src_h sky_frac  ->  x y w h",
    ]
    for src_w, src_h, why in SOURCES:
        lines.append(f"# {src_w}x{src_h}: {why}")
        for sky in SKY_FRACS:
            # The two crops compose, so the region is the second applied inside the
            # first. This mirrors what the pipeline does frame by frame.
            cx, cy, cw, ch = center_crop_aspect(src_w, src_h, target)
            gx, gy, gw, gh = geometry_crop(cw, ch, target, sky)
            lines.append(f"region {src_w} {src_h} {sky!r} {cx + gx} {cy + gy} {gw} {gh}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(SOURCES) * len(SKY_FRACS)} regions)")


if __name__ == "__main__":
    main()
